### ISSUE TITLE
TOTK: (Request) Add pins to map

### ISSUE THREAD

**Issue by Shideravan** [marcrobledo/savegame-editors#216] opened 2023-05-20 17:42 UTC
This is my favorite feature in the BotW save editor. In fact, it’s the only one I really use. Tracking Korok seeds this way is much more fun, so thank you! Now, I would like to ask if there are plans to add this feature to Tears of the Kingdom as well. With so many collectibles and resources to track, it would be incredibly helpful to be able to verify what’s missing from the save and automatically mark these collectibles for easy finding. 
Thank you!

https://www.ign.com/maps/the-legend-of-zelda-tears-of-the-kingdom/hyrule

**Comment by marcrobledo** [comment] 2023-05-21 07:41
Duplicate of #183

**Closed by marcrobledo** 2023-05-21 07:41 UTC
