### ISSUE TITLE
Maybe add The Intro Master Sword

### ISSUE THREAD

**Issue by FehlBan** [marcrobledo/savegame-editors#211] opened 2023-05-20 14:34 UTC
Maybe some People want to use the Mastersword from the Intro cause it is unbreakable the ID is Weapon_Sword_070

**Comment by MrKatzenGaming** [comment] 2023-05-20 22:16
correction: the id of the intro master sword is Weapon_Sword_77 not Weapon_Sword_70

**Comment by ApacheThunder** [comment] 2023-05-21 00:35
It appears one of yesterday's commits may have added it. I opened an old save from before I got it and Weapon_Sword_077 shows up at the bottom of the drop down list. ;)

**Comment by marcrobledo** [comment] 2023-05-21 07:34
Duplicate of #208

**Closed by marcrobledo** 2023-05-21 07:34 UTC
