### ISSUE TITLE
[Totk] Can't save game after import of edited progress

### ISSUE THREAD

**Issue by schmidsgo** [marcrobledo/savegame-editors#289] opened 2023-05-31 14:04 UTC
I tried to edit some item quantities in my save file. When i load the edited save file the changes are applied but as soon as the game auto saves or i do a manual save the game crashes.
I even tried it without any changes. Upload progress.sav and download the "new" one without any changes and i get the same problem.
Is it just me or is it a bug in the editor?

**Comment by schmidsgo** [comment] 2023-05-31 14:35
I was able to find a solution. 
To be able to save the new file you have to delete all other save files.
The structure in Ryzujinx looks somthing like this:
0000000000000001
--0
----slot00
---- ...
--1
----slot00
---- ..
--.lock
--ExtraData0
--ExtraData1

You have to delete all files exept for the folder "0" and inside this folder the slot which is the most recent. Then ediet the progress.sav and start the game. Now it is possible to save the game again.
Maybe i can help someone out with this.
I got the idea from this reddit post: https://www.reddit.com/r/NewYuzuPiracy/comments/13idklq/comment/jkfc90v/?utm_source=share&utm_medium=web2x&context=3

**Comment by fxrs** [comment] 2023-05-31 17:25
Should be a duplicate of  [#5024](https://github.com/Ryujinx/Ryujinx/issues/5024).
The problem seems to be that the file is still "open". 

I had similar problems after only checking the save file in the editor without making changes. Auto-save took minutes, manual save was stuck in "infinite save".
Rebooting fixed it for me.

**Comment by marcrobledo** [comment] 2023-06-03 07:04
Read the [FAQ](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ) for possible solutions.

**Closed by marcrobledo** 2023-06-03 07:04 UTC
