### ISSUE TITLE
TOTK Request Editable Weapon Modifiers

### ISSUE THREAD

**Issue by Karlos007** [marcrobledo/savegame-editors#191] opened 2023-05-17 07:51 UTC
B6EEDE09:No Bonus
A9384C6C:Attack ↑
DAD10617:Attack ↑↑
D5CAD39B:Durability ↑
B2C943EE:Durability ↑↑
7D505BC4:(Bow) Quick Shot
934069CD:(Bow) Arrow Shot x5
B3C94E5:(Shield) Block ↑↑
9659C804:(Weapon) Throw ↑↑
D0EFAC53:(Weapon) Critical Hit +

![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/243ae114-ce21-4705-aa44-cfe6ee77bceb)
A +100 Attack ↑↑ looks like this

**Comment by marcrobledo** [comment] 2023-05-17 09:31
This is a nice contribution, thank you!
I've added the weapon modifier editor in 4e9828b.

Still, I'm not sure about power...
Is it confirmed that power is now a fixed value independent of the modifier? BOTW was different if I recall correctly: you chose a modifier then a value for that modifier.
Do we have any more information on that?

**Comment by Karlos007** [comment] 2023-05-17 09:39
In your editor the first box is durability
the second is the mod value (on a legit weapon the max is 10 for yellow mods) so +10 attack or +10 durability
the third the modifier type

The only changes from botw are that durability can't be 999999, unless you use the durability mod because the game resets higher values to the allowed maximum.

**Comment by marcrobledo** [comment] 2023-05-17 09:43
Oh, that's interesting... so if you use the Durability ↑ or Durability ↑↑ mod, the durability value doesn't reset?

**Comment by marcrobledo** [comment] 2023-05-17 09:44
BTW, I've added the missing modifiers. I haven't tested them, but they should work.

**Comment by marcrobledo** [comment] 2023-05-17 10:05
> Let's say you have a normal Hylian Shield but hacked with 9999 durability If you equip it it will reset to 800 If the modifier is durability +10 it it will reset to 810, the legit max And if the modifier value is durability +1000 it it will reset to 1800 And so on...
> 
> So you can either have a weapon with almost infinite durability or with almost infinite damage/guard In botw you could do both.

Do we know the maximum value the modifier value can be?


> The finishing blow?? I tested and is D0EFAC53:(Weapon) Critical Hit + A white mod that can't be obtained once you are hight level and only get yellow mods

There is another one for bows: 0x54535b3c: Arrow Shot x3???

**Comment by CeruleanSky** [comment] 2023-05-17 20:18
Here is an unedited save with a great eagle bow with x3 shot so a proper value for x3 can be narrowed down, perhaps there is more than one type?
![image](https://github.com/marcrobledo/savegame-editors/assets/2829875/31943d70-5fc5-476b-88b4-f23a3ab22770)

[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11502168/progress.zip)
It loads different in the editor:
![image](https://github.com/marcrobledo/savegame-editors/assets/2829875/97886f66-f3fc-4138-bfc4-5be79ffdfef4)

**Comment by marcrobledo** [comment] 2023-05-17 22:17
Added weapon value editor at last in ad209aa5f573b202379d253ee43f5938ec869912!

Also, added playtime and demon statue container (I don't even know what these are lol) editor (in Master Editor for now) in 1046993c8446f4f66e1d72a79bb713c4e43574d7. @Karlos007 if you are researching for other offsets, it would be great if you created a new issue and post them there.

> Here is an unedited save with a great eagle bow with x3 shot so a proper value for x3 can be narrowed down, perhaps there is more than one type?

That's odd. It has No bonus with a value of 0xffffff. I'll leave the issue open for now, though it's not a priority at the moment.

**Comment by asd123cqp** [comment] 2023-05-18 01:15
I guess now the max durability should also be updated to account for the modifier?

**Comment by Invitation2Hades** [comment] 2023-05-18 01:19
> I guess now the max durability should also be updated to account for the modifier?

Apparently that was already being discussed in this thread.

**Comment by marcrobledo** [comment] 2023-05-18 05:51
> I guess now the max durability should also be updated to account for the modifier?

If I understood @Karlos007 's explanation correctly, max durability always resets to its default value. The value you want to edit to make a weapon more durable is the modifier value.

**Comment by Invitation2Hades** [comment] 2023-05-18 06:00
> > I guess now the max durability should also be updated to account for the modifier?
> 
> If I understood @Karlos007 's explanation correctly, max durability always resets to its default value, no matter what its modifier is. The value you want to edit to make a weapon more durable is the modifier value.

Durability does indeed reset to the max value of the item. However when a modifier is attached, its new higher value is the new max. So like for the example I used before you closed the issue, Hylian Shield max without modifiers is 800, however with a modifier like lets say durability up +10, the new max it should reset to is now 810.

**Comment by Karlos007** [comment] 2023-05-18 06:06
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/776eb1a4-fab0-46f7-96fa-efca3fd619b1)
basically both values should be high

Max durability is the base plus the modifier value

**Comment by LittleFive55555** [comment] 2023-05-18 16:10
Hi, bro. I wonder if fusing things may cause my durability hack not work. I hacked a magic wand to durability++2100000000. I fused that magic wand with a ruby to make a fire magic wand but after I used it for a few times, it was broken.

**Comment by asd123cqp** [comment] 2023-05-18 17:20
> Hi, bro. I wonder if fusing things may cause my durability hack not work. I hacked a magic wand to durability++2100000000. I fused that magic wand with a ruby to make a fire magic wand but after I used it for a few times, it was broken.

Per @Karlos007, this is because currently the max cap added [584cec1](https://github.com/marcrobledo/savegame-editors/commit/584cec157ef4729be0a64b7a4758dc012d49b12c) does not account for the modifier value. You may remove the cap locally from [zelda-totk.js](https://github.com/marcrobledo/savegame-editors/blob/12a104177bfb8d0d192002ba8969a86357725534/zelda-totk/zelda-totk.js#L340) for now and set the durability to the real max (refer to the comment above yours) until a proper fix is in place.

**Comment by Karlos007** [comment] 2023-05-19 08:36
editor seems to work fine with update v1.1.1

**Comment by marcrobledo** [comment] 2023-05-19 18:17
Should be fixed now in c251d26!

**Closed** 2023-05-23 10:30 UTC
