### ISSUE TITLE
TOTK Request: Horse editor

### ISSUE THREAD

**Issue by MJr0019** [marcrobledo/savegame-editors#169] opened 2023-05-12 15:16 UTC
First I would like to thank you for all your work so far.

thank you very much

could you add the function to edit the colors of the horses?

-------------------------------------------------------------------------------------------

En primer lugar me gustaría darle las gracias por todo su trabajo hasta ahora.

muchas gracias

¿podrías agregar la función para editar los colores de los caballos?

**Comment by marcrobledo** [comment] 2023-05-16 06:07
The issue title mentions BOTW, I'm not sure if that was a mistake. You can edit BOTW horses already.
Did you mean TOTK? If that's the case, the horse editor can come if you provide a savegame with horse data. It will be very helpful if it has five horses and you also provide their names, saddles, etc.

**Comment by JonJaded** [comment] 2023-05-16 20:45
Here's my save. Hopes this helps.

`Askye 		-MAX BOND-	Towing Harness`
`Pips 		-MAX BOND- 	Default Harness`
`Blindye 	-95 BOND- 	Default Harness`
`Marledo 	-36 BOND- 	Default Harness`
`Ichekse 	-00 BOND- 	Towing Harness`
`Jadeite 	-30 BOND- 	Towing Harness 	[1744 -1923 0012] `
`Untamed Horse 	-?? BOND- 	No Harness 	[1735 -1942 0012] `


[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11491879/progress.zip)

**Comment by JonJaded** [comment] 2023-05-17 06:11
Question though, for my morbid curiousity. I opened my save in HxD and I'm just wondering how does parsing the info work?  It's clearly not plaintext so how do you 'unencrypt' or demangle the save data structure? Is it just diffing until you find the pattern?

**Comment by Karlos007** [comment] 2023-05-17 09:39
Offsets for v1.0.0 (for v1.1.0 need to add +0x38):

0010E008:Horse Name 01
0010E028:Horse Name 02
...+0x20

0008A0F0:Horse Type 01
0008A130:Horse Type 02
...+0x40

GameRomHorse00L is the Large Horse from botw
GameRomHorseGold is the new Gold Horse
GameRomHorse01L is the new Large White Horse

The only problem is that changing the horse type doesn't change the image preview when choosing horses.
Also need to find the stats and equipment.

**Comment by JonJaded** [comment] 2023-05-17 15:27
> The only problem is that changing the horse type doesn't change the image preview when choosing horses. Also need to find the stats and equipment.

This is another issue I've heard multiple times. The game seems to have a cached copy of a lot of the thumbnails which don't dynamicly update (likely because the game doesn't expect them to spontaneously change.) Not sure on what a fix would be.

**Comment by Ozymandias07** [comment] 2023-05-18 20:50
When ever I open my save in the editor I cant edit my horses. I have horses registered, but the tab is grayed out and I cant click on it. Is there something I am doing wrong?

**Comment by JonJaded** [comment] 2023-05-18 20:56
> but the tab is grayed out

The feature is not yet implemented. It has not even been a week since release; gotta slow down a bit.

**Comment by Ozymandias07** [comment] 2023-05-18 20:58
oh whoops

**Comment by JonJaded** [comment] 2023-05-18 21:03
Oh no, the threads that say closed are the dupe thread. This one is still open. If you want to help marcro, please zip your save file and give a table of the horse information as I did in here. (Reply 3)

https://github.com/marcrobledo/savegame-editors/issues/169#issuecomment-1550336369_

**Comment by JonJaded** [comment] 2023-05-19 18:57
>Giant Horse equipment 

Ah you're right! One of my horses is the giant horse, they use a seperate harness type as compared to regular horses. I made a slight error in my horse inventory labeling (specifically Pips) @marcrobledo , it's fixed now.

**Comment by marcrobledo** [comment] 2023-05-19 20:33
Added a very basic horse editor, it can edit the horse type for now.

**Comment by marcrobledo** [comment] 2023-05-21 07:37
The horse name editor is currently disabled for security reasons.

Can anyone share a savegame with japanese/chinese/korean characters for horses so I can check if it's safe?

**Comment by DomSirk** [comment] 2023-05-21 07:37
Add Horse Name Changer Please

**Comment by Karlos007** [comment] 2023-05-21 08:05
> The horse name editor is currently disabled for security reasons.
> 
> Can anyone share a savegame with japanese/chinese/korean characters for horses so I can check if it's safe?

![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/a29106f8-c389-42bf-ad51-32cc26b9d1d0)
[Ryujinx.zip](https://github.com/marcrobledo/savegame-editors/files/11523985/Ryujinx.zip)
I tamed 3 horses on slots 7 8 9
game v1.1.1

**Comment by JonJaded** [comment] 2023-05-21 08:11
The game still has the same 9 character limit from BOTW. I saw in the sav file that after each character of a horses name is a`00` spacer, and I'm sure that's what you're worried about.

**Comment by marcrobledo** [comment] 2023-05-21 08:11
Oh, wait, so there is room for more than six horses? I recall someone here saying it was six.
That would explain why the savegame horse data array length is 10.

**Comment by DomSirk** [comment] 2023-05-21 08:15
Yes you unlock more slots by getting points at the stables

**Comment by JonJaded** [comment] 2023-05-21 08:19
> Oh, wait, so there is room for more than six horses?

Yes there is, I definetly should've mentioned that. you start with 6 slots, (because the game transfers over 5 of your horses from BOTW + first horse you capture.) If it doesn't transfer, those slots are still available to you. You can then later upgrade your slot count after a certain amount of tickets at the stables.

As you said, 10 is the max.

**Comment by Karlos007** [comment] 2023-05-21 08:25
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/dcd9712b-b582-40c0-926c-7a5fb379d768)
The slot 6 should be GameRomHorseSpPattern
Is a normal looking horse but you get it from a quest.
Maybe it's a unique type.

**Comment by marcrobledo** [comment] 2023-05-21 09:07
Added horse name editor in d9e7394!

**Comment by MJr0019** [comment] 2023-05-21 16:10
Thanks for add editor

**Comment by JonJaded** [comment] 2023-05-21 17:26
Can I request this topic to be reopened? There are a couple of things that could be implemented.

**Final additions:**

- Adding horses directly (up to 10)
- Saddle editor

**Unnecessary stuff:**

- Untamed horse type
- Untamed horse location

_ Really uneeded finishing touches:_

- Bond editor? 
(Bond is very easy to max out so we probably don't need that.)

**Comment by JonJaded** [comment] 2023-05-21 17:39
> ![image](https://user-images.githubusercontent.com/23475289/239729022-dcd9712b-b582-40c0-926c-7a5fb379d768.png)
> The slot 6 should be GameRomHorseSpPattern
> Is a normal looking horse but you get it from a quest.

Would you happen to know if this changes the cap on the amount of horses (like in #221) where's it's a 10 + 1 reserved or is this a unique horse?

If you tell me where you got this horse quest, I can go test.

**Comment by Karlos007** [comment] 2023-05-21 17:42
> > ![image](https://user-images.githubusercontent.com/23475289/239729022-dcd9712b-b582-40c0-926c-7a5fb379d768.png)
> > The slot 6 should be GameRomHorseSpPattern
> > Is a normal looking horse but you get it from a quest.
> 
> Would you happen to know if this changes the cap on the amount of horses (like in #221) where's it's a 10 + 1 reserved or is this a unique horse?
> 
> If you tell me where you got this horse quest, I can go test.

It's on Lookout Landing but a bit later in the story when you build the stable
It doesn't seem to change the cap

**Comment by ApacheThunder** [comment] 2023-05-21 23:50
I have tested the current version of the horse editor and it looks like Satori and the bone horses can be edited in without the game crashing (like it would in BoTW). They have bugged hairdo's since the current horse editor is limited and the horse I replaced with the bone/Satori ones inherited the equipment settings/stats of the horse it was replacing. The Satori horse ends in Nushi and the bone ones...end in bone. I specifically tested the one that ended in AllDay. Did not try pulling out the non AllDay one. That one might have died the instant I pulled him out since it was day time and I'm not sure how the game would handle it. The AllDay one didn't care that it was day time.

Another interesting note, the Satori one did not run off and vanish like he normally does so save editing him into the stable seemed to make him permanent. Though currently does not have his normal infinite stamina stats due to the limited editor. :P

**Comment by Lucifiish** [comment] 2023-05-22 15:16
Hey! I know you have a lot on your plate, and I really, really appreciate you going out of your way to make all this for us! That said, I wanted to add on to this here and mention that, in Yuzu, a lot of the horse labels can't seem to change - patterns don't seem to change when changing the game rom horse. I'm not sure if that's because of the upgrade system, but I felt it wqas worth mentioning. It's not a huge deal to me, though.

The main thing I wanted to request was if you could attempt to port over the horse gear and mane editing feature from the BotW editor. I edited in the old giant horse from BotW, but it still has the old mane and saddle, and I haven't been able to switch it over to the giant horse gear and mane. I'd like to be able to switch them over, if possible

**Comment by ApacheThunder** [comment] 2023-05-22 16:59
Since I confirmed  Satori and Skeleton horses don't crash the game upon editing them into the stable it might be worth researching if you could assign wildlife stuff to horse slots too. ;)

Though understandable if this isn't possible if the game doesn't have flags for them. Interesting the game would have flags for Satori and skeleton horses though. Perhaps a mistake of the editor? I checked the BoTW one and it appears they no longer list Satori and skeleton horses. I definitely do remember being able to assign them at one point. The editor at the time didn't have ability to alter equipment though so improper equipment settings might be why they crashed the game? Would be interesting to revisit that.

The current editor preserves the stats/equipment of the horse previously in the slot when assigning a different one and this "might" be why Satori/Skeleton horses aren't crashing the game this time around.

**Comment by KrisCris** [comment] 2023-05-23 03:34
In BotW, I replaced one of my horses with Satori, it didn't crash the game - but rather didn't show up at all when I tried to summon it. 

In TotK however, Satori shows up without any problem, but it has the additional hair from the horse replaced lol. Would be interesting to see if it's possible to not assign Satori any equipment or hair.

**Comment by ddaversa** [comment] 2023-05-23 21:21
FYI

Changing the horse type in the editor seems to affect the model of the horse, however, the stats & avatar/picture of the horse are unaffected.

No screenshot, but just for example, I had a random horse, switched it to HorseZelda, and the model is now white, but the picture stayed black, with the previous horse's stats.

I know it's not a bug, it's a work in progress, just thought it could be useful to share.

**Comment by Lucifiish** [comment] 2023-05-24 00:22
> I have tested the current version of the horse editor and it looks like Satori and the bone horses can be edited in without the game crashing (like it would in BoTW but that was a long time ago. Maybe the horse editor at the time wasn't setup to change equipment and perhaps having no equipment assigned is why they crashed the game? Someone should revisit that. ;) )
> 
> They have bugged hairdo's since the current horse editor is limited and the horse I replaced with the bone/Satori ones inherited the equipment settings/stats of the horse it was replacing. The Satori horse ends in Nushi and the bone ones...end in bone. I specifically tested the one that ended in AllDay. Did not try pulling out the non AllDay one. That one might have died the instant I pulled him out since it was day time and I'm not sure how the game would handle it. The AllDay one didn't care that it was day time.
> 
> Another interesting note, the Satori one did not run off and vanish like he normally does so save editing him into the stable seemed to make him permanent. Though currently does not have his normal infinite stamina stats due to the limited editor. :P
> 
> I was able to assign different equipment to both horses without issue though I wonder if that continues to be the case once the horse stats are properly set for them.

When you say assign gear, do you mean in-game or via a save editor? I edited in horse gear to my inventory and it bugged my save file and now I can't change horse gear in game, so I'm trying to find another way to change horse data and mane if possible. Do you know how I could go about that?

**Comment by marcrobledo** [comment] 2023-05-25 19:52
Check the horse editor and you'll get some little new features!

Still need to find values for strength and stamina stats and the special Royal White Stallion type value, so feel free to post some (unmoded) savegames with horses with different strength and stamina and with that special horse, it will help a lot.

**Comment by marcrobledo** [comment] 2023-05-25 22:17
And Strength and Stamina editors are up!

**Comment by JonJaded** [comment] 2023-05-26 02:19
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11570826/progress.zip)
Here's my horse with RWS. Last horse. My other horses have different bodies though. (Like I tried to change one of my horses to Epona but it did not work in game.)
So I wouldn't use their data as vanilla. RWS is 100% untouched though.

**Comment by Karlos007** [comment] 2023-05-27 07:01
![0100f2c0115b6000_2023-05-27_08-34-32-119](https://github.com/marcrobledo/savegame-editors/assets/23475289/db4cc02e-838c-4927-8dbb-9e8114f09ec7)
![0100f2c0115b6000_2023-05-27_08-36-56-557](https://github.com/marcrobledo/savegame-editors/assets/23475289/c5d99311-163a-4980-90b7-1a538875e2c1)


The editor is awersome, 
I found a workaround for the in game icon, but requires editing an unregistered horse (00053E40).
At firsts looks like it doesn't change but after registering the icons get updated.

Note 1: The mane may require to be edited for giant horses.
Note 2: Killing and reviving doesn't update the icon.

**Comment by marcrobledo** [comment] 2023-05-27 08:43
Added a new untested horse: Donkey.

**Comment by Xario123** [comment] 2023-05-27 22:17
You are really doing a great job with this program. Thank you!

However, I ran into a problem. I hope the attached archive will help you to improve the save editor. I put many screenshots and the 3 progress.sav to illustrate what happens with horses.

I have a game save from "TOTK" with which I recovered 5 horses from "BOTW". ("source_save" folder of the zip archive).

I load the "progress.sav" file from the "source_save" folder in the save editor to copy the data to transfer it to the "progress.sav" file from the "unmodified_save" folder.

The result is in the "progress.sav" file in the "modified_save" folder. it doesn't match the game save from "source_save".
[saves.zip](https://github.com/marcrobledo/savegame-editors/files/11583123/saves.zip)

**Comment by geogeim** [comment] 2023-05-28 04:56
Lord of the Mountain works, sort of.
If you overwrite a horse that is already taken out with these values it will appear ok, without extra mane and bridle
![image](https://github.com/marcrobledo/savegame-editors/assets/16436533/15de1b62-c054-4c48-9835-b785a4229d88)
![image](https://github.com/marcrobledo/savegame-editors/assets/16436533/26a18775-d89e-417a-85d7-d982c8ca683d)
But if you put it back in the stable or recall it it will glitch out :)
Also if you set the stamina to infinite it will throw you down when you try to go faster :)

**Comment by Zullivan1987** [comment] 2023-05-28 16:26
> ![0100f2c0115b6000_2023-05-27_08-34-32-119](https://user-images.githubusercontent.com/23475289/241363368-db4cc02e-838c-4927-8dbb-9e8114f09ec7.jpg) ![0100f2c0115b6000_2023-05-27_08-36-56-557](https://user-images.githubusercontent.com/23475289/241363373-c5d99311-163a-4980-90b7-1a538875e2c1.jpg)
> 
> The editor is awersome, I found a workaround for the in game icon, but requires editing an unregistered horse (00053E40). At firsts looks like it doesn't change but after registering the icons get updated.
> 
> Note 1: The mane may require to be edited for giant horses. Note 2: Killing and reviving doesn't update the icon.

Can you add the function to delete at least the horses that are in the stable? I would like the option to delete or free horses to exist since the only option to add more horses to the game is to kill them and send them to the fairy's cemetery.

**Comment by neico** [comment] 2023-05-28 17:09
While I approve of the possibility to remove horses (and maybe to reorder them),
you can replace horses natively in-game if you hit the current limit, basically overriding a slot.

**Comment by ApacheThunder** [comment] 2023-05-28 22:09
So I've fiddled with the horse editor code to see what the limits are for hte game and here's my findings:

1. Setting Pull/Speed/etc stats beyond the normal maxium crashes teh game when you attempt to mount the horse. (so sadly no Mach 5 horses that can pull mountains. :( )
2. The above crash does not occur for stamina! I was able to set stamina to 9 on a horse and while the UI glitched a bit it seems to actually register that I have 9 stamina!

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/3528ee0b-f280-4c20-9e46-903df531c54e)
(it appears 7 is the cut off before it it displays incorrectly)

Also setting stamina to 1 is also possible so if you want the lamest horse to ever exist you can do that too. Satori's special version of infinite stamina doesn't appear be possible it looks like. The value of 1 which I thought might be it just set him to 1 stamina bar and values above 5 just adds more bars of stamina to him. So he only gets his infinite stat in the wild? Maybe there's a unique int value for it but someone would have to datamine that I suppose.

Also you can set the other stats to 1 too though for some reason. So while you can't go above 5 stars on the other stats without the game crashing it seems you can set them to 1 star. Behold the lamest possible horse!

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/c5c1bc43-dacc-4e5b-9b72-250a187e354e)


:P

Anyways I suggest adding a new selection to the Stamina drop down menu. Perhaps a Custom entry which enables a text field that lets the user type in the custom value they want. Limit it to valid int values of coarse and prevent the user from using negative values as I'm not sure how the game would handle that. :P

**Comment by ApacheThunder** [comment] 2023-05-28 22:22
> Also if you set the stamina to infinite it will throw you down when you try to go faster :)

I believe that might be due to his temperment stat? The editor can't currently set that. It might be something set by the horse type and not something the editor can change. A wild temperment = he kicks you off if you try to overwork them. Though I could be wrong. I forget what temperment the Giant White Stalion is and he's also a horse with infinite stamina and he doesn't kick you off if you try to hit A too much.

**Comment by ApacheThunder** [comment] 2023-05-29 01:36
Ok here's my test results. It looks like you could use most animal actor IDs without much game breakage beyond not being able to ride them. Which is interesting. I am curious as to why I can spawn animals this way but not NPCs. :(

Animal_Wolf_A - Spawns a wolf that runs away. If you catch up to him he'll attack you. Interesting note if you kill him he does not vanish into meat and remains as a corpse. Stable doesn't recognize him as dead so you can just take him out again. (this likely applies to all animals spawned this way)
Animal_Donkey_B - Spawns with working collision. Can use donkey equipment but it doesn't let Link mount him. I believe this was the proper actor name used for the donkey's seen in the overworld. (no idea where the other name came from. It seems some horse names don't correspond to file names found in the game's AS folder so there might be a string table somewhere for this?)
Animal_Donkey_C - Works kinda. Shows up with no equipment. Has no collision and you can't mount him. (though it does react to sword slashes)
Animal_Cow_A - Spawns cow. Has collision and reacts to sword slashes (even walks to a different location to get away). Can't mount him.


It seems most if not all the Animal type Actor IDs work. I don't have the time to test them all so I'll post them here for others to experiment with:

Animal_Bear_A
Animal_Boar_A
Animal_Bull_A
Animal_Cassowary_A
Animal_Cow_A
Animal_Crow_A
Animal_Deer_A
Animal_Dog_A
Animal_Donkey_B
Animal_Donkey_C
Animal_Elk_A
Animal_Fish_A
Animal_Fish_Sell_B
Animal_Fox_A
Animal_Goat_B
Animal_Gull_A
Animal_Gull_Swarm
Animal_Hawk_A
Animal_Heron_A
Animal_Horse_A
Animal_Horse_A_00L
Animal_Insect_Beetle
Animal_Insect_Crab
Animal_Insect_Fairy
Animal_Insect_FireFly
Animal_Insect_Lizard
Animal_Insect_N
Animal_Kokko_A
Animal_LittleBird_A
Animal_Pao_A
Animal_Pigeon_A
Animal_RupeeRabbit_A
Animal_Sheep_A
Animal_SkyCassowary_A
Animal_Squirrel_A
Animal_Sunazarashi
Animal_Sunazarashi_B
Animal_SunazarashiSP_C
Animal_UnderInsect
Animal_WildDuck_A
Animal_WildGoat_A
Animal_Wolf_A


Most animals can be killed and their corpses will remain until you respawn them at a stable. It seems they don't register as dead to the stable system so I suppose you could do some funny things with the corpses if you want.

Even normal horse corpses despawn after awhile but the animal ones won't. That also means animals that despawn after they run away can't despawn either. That includes blupees which usually despawn pretty quickly.

I tested some other non animal stuff like NPCs and enemies. Most just result in glitched underworld camera view with nothing spawning.

I did get something to show up kinda with Npc_Zelda_Opening. It appears non supported stuff sometimes spawn something but they appear out of bounds for some reason. Case in point the Zelda NPC from prologue. She is briefly seen falling in an unknown area underground before going off screen. I think maybe a collision issue? Could be the area under the normal spawn spot for horses removed from the stable. But partially/fully clipped into ground causing them to fall into the void? I tried BackseatKorok as well which appears to be the actor name for those backpack Koroks but sadly no Koroks on demand with that one. I can't tell if anything at all spawns in the void with that one either.

**Comment by VIXIVIXIV** [comment] 2023-05-29 03:09
I did some messing around, and I think the horse editor right now has a major flaw (and the BOTW editor has this flaw too, but nobody cared because they chose a horse for looks first and modded in the stats after the fact): the color data is completely ignored. The "horse type" field probably only sets the coat pattern and muzzle pattern, the colorway (base color, pattern color, and muzzle color) are stored elsewhere in the save file and cannot be edited with the current editor.

For example, I took the transferred BOTW horse data from a fresh TOTK save, copied just the horse types, and then edited in the missing fields for health, name, bond, etc. The horses show up as registered at stables, but their coats in their profile pictures are blacked out and their manes are white, probably because the color data is missing. Taking them out grants a horse with a default coat color which doesn't match the original BOTW save in the slightest.

This color issue may also explain why changing the horse type doesn't update the profile picture, it's because it's an irrelevant variable. The profile picture has a separate, reduced "type" (because if you ignore the differences in body patterns, there are only like 5 distinct muzzle patterns), and then populates the rest of the picture using the color data.

So, fair warning to those wanting to backport their BOTW horses: currently not possible unless you go to the effort of seeking out horses with matching color sets which you'll then change the type to match.

**Comment by ApacheThunder** [comment] 2023-05-29 04:26
I found another folder with a more complete list of actor names. I managed to spawn prolog zelda's torch and now have it in my inventory:

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/29f32283-3951-4d58-83af-2c682c01503c)
![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/6cb27e58-9bdd-460b-9f74-4fbdea9c9082)


An unexpected way of finding a new weapon ID but hey it works:

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/6346a57c-0a1a-49c7-a42a-fef24a4739ba)


Maybe add that to the weapon editor. :P

**Comment by KrisCris** [comment] 2023-06-01 02:20
Will it be possible to edit untamed horse, same as the one in BotW editor?

**Comment by ApacheThunder** [comment] 2023-06-01 04:08
Untamed horses show up as a different actor ID. As I recall the base actor ID they all live under. Here's their Actor IDs:

Animal_Horse_A
Animal_Horse_A_00L
Animal_Horse_A_01L
Animal_Horse_A_Epona
Animal_Horse_A_Gold
Animal_Horse_A_SpPattern
Animal_Horse_A_Zelda
Animal_Horse_B
Animal_Horse_NoMove
Animal_Horse_Nushi

Not sure what the NoMove one. That one maybe ones seen hanging out inside the stable pens.

**Comment by geogeim** [comment] 2023-06-01 07:50
> Not sure what the NoMove one. That one maybe ones seen hanging out inside the stable pens. It doesn't looks like these IDs are usable in the stables though. Tried Animal_Horse_Nushi and got nothing. (the camera in the void bug happens if you give it a actor ID that either doesn't exist or isn't a compatible actor for the stables)

If you get the weird camera it probably means you don't have a valid saddle/mane/reins.

**Comment by geogeim** [comment] 2023-06-01 15:50
here are a few interesting ones:

Dm_Npc_Zelda_Catch // go where the horse sign is on map and press A, it will play the end game sequence
Enemy_Dragon_Darkness // will spawn dragon ganon, you can fight him

**Comment by ApacheThunder** [comment] 2023-06-02 00:35
> > Not sure what the NoMove one. That one maybe ones seen hanging out inside the stable pens. It doesn't looks like these IDs are usable in the stables though. Tried Animal_Horse_Nushi and got nothing. (the camera in the void bug happens if you give it a actor ID that either doesn't exist or isn't a compatible actor for the stables)
> 
> If you get the weird camera it probably means you don't have a valid saddle/mane/reins.

I always have those set so it's just that some Actor IDs aren't recognized by the stable. I had rains/saddles defined in all my tests. There are many NPCs I've spawned that the saddle/rains don't attach to or appear on so it's not an issue of them not being able to attach to anything. (though it does look super cursed when you get a NPC combo that does accept a mane/bridle/saddle. I think Tulin was one NPC that it worked on. :P )

**Comment by luciilesbo** [comment] 2023-06-05 06:22
is it possible to get a deer?

**Comment by nbdeity** [comment] 2023-06-14 20:24
Sorry to add onto this, but does the lord of the mountain have to be put over a specific horse in order to enable physics for the tail / antennae /etc?

**Comment by marcrobledo** [comment] 2023-08-10 15:04
> It's personally but can we have function that allow to switch horse slot (change horse order) ?

You can export a horse into json format then reimport it in any other slot. That would allow you to switch horse slots.

**Comment by Peduls** [comment] 2023-08-14 02:40
You can bypass the 9 character limit when naming your horse using your BotW Save Editor. It'd be great if you could add that into the TotK Save Editor as well.

**Comment by marcrobledo** [comment] 2023-08-16 17:34
> You can bypass the 9 character limit when naming your horse using your BotW Save Editor. It'd be great if you could add that into the TotK Save Editor as well.

I recall I tried that back when the game was released and I think it was impossible (I might be wrong though).

If anyone wants to try, just change the value at `zelda-totk.class.horse`, line 112. Set `maxLength` to anything longer than 9 (but shorter than 16) and see if it works.

**Closed** 2024-07-24 17:33 UTC
Labels: enhancement

**Comment by Yashirow** [comment] 2025-09-29 18:30
Sorry to bump this, but I didn’t see any official statement on it (aside from the "*" before the horse’s name). The special horses (so the ones with the *) aren’t stable-friendly, right? When I try to take them out, they appear invisible below the map and the bugged customize equipment list shows up with 9,999 rupees plus German text.
