### ISSUE TITLE
[BotW] Invalid Savegame

### ISSUE THREAD

**Issue by ivpiteriv** [marcrobledo/savegame-editors#110] opened 2020-02-03 16:37 UTC
I'm getting an "Invalid savegame file" Error when I try to upload my savegame file from BotW. 
I'm using Cemu 17. 
The game, Zelda BotW, is running with mods and I assume this is where the issue lies. 
I'm using the [Crafting Mod ](https://gamebanana.com/craftings/103) which adds new items to the game. 
Is it possible to fix that and make the editor simply overlook the unknown items? 

[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/4148911/game_data.zip)

Edit: I've removed the said mod and the items aren't listed in my inventory any longer, but it still gives me the same error.
[Uploading game_data.zip…]()

**Comment by Bruce-Oases** [comment] 2020-02-11 08:30
Hello, I have found the cause of this problem.Changes in archive size caused by Mod.The editor has a process for verifying the archive size, so it is not recognized properly.You can change the file size by default （savegame-editors\zelda-botw\zelda-botw.js  SavegameEditor.Constants.FILESIZE）or skip the validation step（let it always return true ：savegame-editors\zelda-botw\zelda-botw.js  _checkValidSavegameByConsole.）

**Comment by jaymayott** [comment] 2020-02-14 07:47
> 
> 
> Hello, I have found the cause of this problem.Changes in archive size caused by Mod.The editor has a process for verifying the archive size, so it is not recognized properly.You can change the file size by default （savegame-editors\zelda-botw\zelda-botw.js SavegameEditor.Constants.FILESIZE）or skip the validation step（let it always return true ：savegame-editors\zelda-botw\zelda-botw.js _checkValidSavegameByConsole.）

How does one do this?

**Comment by ivpiteriv** [comment] 2020-02-15 11:27
> Hello, I have found the cause of this problem.Changes in archive size caused by Mod.The editor has a process for verifying the archive size, so it is not recognized properly.You can change the file size by default （savegame-editors\zelda-botw\zelda-botw.js SavegameEditor.Constants.FILESIZE）or skip the validation step（let it always return true ：savegame-editors\zelda-botw\zelda-botw.js _checkValidSavegameByConsole.）

do you think it's possible to adjust the savefile instead? 
 I think we won't be able to fix the issue without hosting the whole thing by ourselves otherwise..

**Comment by marcrobledo** [comment] 2020-02-15 11:47
I've been reading you guys.

I'll add support for modded savegames, give me a couple of days.

**Comment by ivpiteriv** [comment] 2020-02-15 11:47
> I've been reading you guys.
> 
> I'll add support for modded savegames, give me a couple of days.

Many thanks!!

**Comment by marcrobledo** [comment] 2020-02-16 22:36
Fixed in de1aa9f
Let me know if it works correctly with your savegames.

**Comment by jaymayott** [comment] 2020-02-17 05:39
Still giving me the invalid save game, if it helps I have the hero blight
mod and the moonslayer mod.

**Comment by jaymayott** [comment] 2020-02-17 05:39
I also dont know how to change the file size or I would have already done
so, I've looked it up but I guess I'm just not looking in the right places.

**Comment by marcrobledo** [comment] 2020-02-17 07:02
@jaymayott post your savegame and I'll take a look.

**Comment by jaymayott** [comment] 2020-02-17 07:13
Here is my main save file with the mods in.

**Comment by jaymayott** [comment] 2020-02-17 07:14
Okay wait a moment, I just tried loading the save again and it didnt give
me an invalid error this time, i think you got it fixed.

**Comment by ivpiteriv** [comment] 2020-02-17 10:07
Fixed for me! 

But editing Horses seems to not work..

**Comment by Davillion11** [comment] 2020-05-25 07:26
where can i download the botw editor v1.6 for switch?

**Closed** 2020-05-25 14:58 UTC
