### ISSUE TITLE
Add ability to add item in weapons, armor, shields and bows categories

### ISSUE THREAD

**Issue by levine22** [marcrobledo/savegame-editors#195] opened 2023-05-17 20:17 UTC
Hi marcrobledo
love your save editor. can you please add the ability to add items in the following categories: weapons, shields, armor, bows. it seems that in these categories we are limited to 5 inventory slots when we have many more, up to 100 slots in some. we have this ability for materials and zonai devices, it would be really cool to have it as well in weapons, armor, shields, bows.

**Comment by marcrobledo** [comment] 2023-05-17 20:26
Duplicate of #181

**Closed by marcrobledo** 2023-05-17 20:26 UTC

**Comment by levine22** [comment] 2023-05-17 20:29
sorry must of missed it, thanks!
