### ISSUE TITLE
Loading a save file won't work

### ISSUE THREAD

**Issue by Luneyes** [marcrobledo/savegame-editors#5] opened 2017-03-30 00:06 UTC
Hi!
Your project looks really good but I can't manage to load a game file... 
When I choose a file, nothing happens.

I wanted to test your tool with a EUR BotW save file.
The name of the file is good (game_data.sav). I tested your tool on Chrome, Firefox, and IE. Same everywhere, the file just doesn't load and nothing happens.
I don't block javascript, I don't use any adblocker or anything that may prevent your code from working correctly.

Can you fix this issue, please?
Thank you and have a nice day!

**Comment by krystiancharubin** [comment] 2017-03-30 03:56
The EUR version game_data.sav are different size from the US version.
This means that it fails the size check that determines which game you are trying to edit.
Forcing it into the BotW editor also doesnt work, it seems EUR version has different offsets also.

**Comment by marcrobledo** [comment] 2017-03-30 06:34
@Luneyes Please, post your game_data.sav so I can take a look at it :-)
@krystiancharubin Can you post an US savegame? It's weird, no one had reported this before, I implied they were the same.

**Comment by Luneyes** [comment] 2017-03-30 11:06
It's a EUR save so that's the problem.
Here is a link to download my save if you want to take a look:
http://www.mediafire.com/file/92accx7c3jq04s7/game_data.sav

Good luck! :D

**Comment by marcrobledo** [comment] 2017-03-30 18:07
No, that's not the problem. My game is EUR too, and the savegame is different. Do you have the latest update for the game? (Check it out at the title screen).

Anyway, this will be fixed :-)

BTW, can you tell me the exact value of rupees in that savegame?

**Comment by Luneyes** [comment] 2017-03-30 18:48
I noticed that the save isn't the same size of the ones I can find online. Is it because I'm using Cemu?
I saw somebody else having the same problem. I'm not the only one having this bug.

My game version is 1.0.0.

Well... I have 0 rupees on that save. :/

Thank you for your time. Good luck! :)

**Comment by marcrobledo** [comment] 2017-03-31 07:14
Confirmed, it's now because the region but the game version. 1.0.0 and 1.1.x have different file sizes.

**Comment by Luneyes** [comment] 2017-03-31 11:30
Oh... ok!
Good to know. I'll update the game then. :)

You should add a small information text explaining that to avoid confusion. ;)

Bye! Have a nice day!

**Comment by marcrobledo** [comment] 2017-04-04 08:15
This has been fixed!

**Closed by marcrobledo** 2017-04-04 08:15 UTC
