### ISSUE TITLE
TOTK Request Editable Horses

### ISSUE THREAD

**Issue by Karlos007** [marcrobledo/savegame-editors#192] opened 2023-05-17 08:06 UTC
Offsets for v1.0.0 (for v1.1.0 need to add +0x38):

0010E008:Horse Name 01
0010E028:Horse Name 02
...+0x20

0008A0F0:Horse Type 01
0008A130:Horse Type 02
...+0x40

GameRomHorse00L is the Large Horse from botw
GameRomHorseGold is the new Gold Horse
GameRomHorse01L is the new Large White Horse

The only problem is that changing the horse type doesn't change the image preview when choosing horses.
Also need to find the stats and equipment.

**Comment by marcrobledo** [comment] 2023-05-17 09:31
Duplicate of #169. Please repost this there!

**Closed by marcrobledo** 2023-05-17 09:31 UTC
