### ISSUE TITLE
TOTK request: Shrine editor

### ISSUE THREAD

**Issue by KishaPawpad** [marcrobledo/savegame-editors#223] opened 2023-05-21 11:02 UTC
Hi, I'm wondering if it's possible to add a shrine editor like the skyview towers? Found and completed. Must be a lot of work. 

In my case it would help me copy the Switch progress to the PC emulator.

**Comment by marcrobledo** [comment] 2023-05-23 10:33
Duplicate of #199

**Closed by marcrobledo** 2023-05-23 10:33 UTC
