### ISSUE TITLE
Fused world Objects

### ISSUE THREAD

**Issue by sequestersi** [marcrobledo/savegame-editors#295] opened 2023-06-03 03:45 UTC
Currently the options in the Fused Item list are mostly limited to Materials, Weapons, and a few objects. I am hoping that all of the fusable objects can be added - especially the limited ones that are no longer accessible after a quest is completed or the game is otherwise progressed. A prime example of this is the roof piece of the Lookout Landing mini-stable, which can no longer be accessed after slotting it into place in the roof.

The utility of this is that we would then be able to access these objects for building, regardless of how much we have progressed in a save file, in the event that they are discovered to be useful for a particular build.

**Comment by marcrobledo** [comment] 2023-06-03 06:57
Duplicate of #270

**Closed by marcrobledo** 2023-06-03 06:57 UTC
Labels: duplicate
